# Generated by Django 5.0.7 on 2024-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_in_sold',
            field=models.IntegerField(default=0),
        ),
    ]
